#!/usr/bin/env python3
"""Audit report generator for smart contract security findings.

Takes scanner output (JSON) and generates a formatted Markdown audit
report using Jinja2 templates. Includes executive summary, findings
table, detailed findings, and severity statistics.

Usage::

    python report_generator.py --input findings.json --output report.md --protocol-name "Lido"
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    from jinja2 import Environment, BaseLoader
except ImportError:
    print("Error: jinja2 is required. Install with: pip install jinja2", file=sys.stderr)
    sys.exit(1)


# ---------------------------------------------------------------------------
# Report template (Jinja2 Markdown)
# ---------------------------------------------------------------------------

REPORT_TEMPLATE = r"""# {{ protocol_name }} -- Smart Contract Security Audit Report

**Generated**: {{ timestamp }}
**Tool**: Smart Contract Security Scanner (Static Analysis)

---

## Executive Summary

This report presents the findings of an automated static analysis of the
**{{ protocol_name }}** smart contracts. The scanner examined
**{{ stats.files_scanned }}** Solidity files using **{{ stats.analyzers_run }}**
analysis modules in **{{ stats.elapsed_seconds }}** seconds.

{% if total_findings == 0 -%}
**No issues were detected.** The contracts passed all automated checks.
This does not guarantee the absence of vulnerabilities; manual review is
still recommended.
{%- else -%}
A total of **{{ total_findings }}** findings were identified:

| Severity | Count | Percentage |
|----------|------:|------------|
{% for sev in severity_order -%}
{% if severity_counts[sev] > 0 -%}
| {{ sev }} | {{ severity_counts[sev] }} | {{ "%.1f"|format(severity_counts[sev] / total_findings * 100) }}% |
{% endif -%}
{% endfor -%}

{% if critical_count > 0 -%}
**{{ critical_count }} Critical** issue(s) require immediate attention.
{% endif -%}
{% if high_count > 0 -%}
**{{ high_count }} High** severity issue(s) should be addressed before deployment.
{% endif %}
{%- endif %}

### Severity Distribution

```
{% for sev in severity_order -%}
{% if severity_counts[sev] > 0 -%}
{{ "%-15s"|format(sev) }} {{ bar_char * severity_counts[sev] }} {{ severity_counts[sev] }}
{% endif -%}
{% endfor -%}
```

---

## Analyzer Coverage

| Analyzer | Findings |
|----------|----------|
{% for name, count in analyzer_counts.items() -%}
| {{ name }} | {{ count }} |
{% endfor -%}
{% if not analyzer_counts -%}
| (none) | 0 |
{% endif %}

---

## Findings Summary

{% if total_findings == 0 -%}
No findings to display.
{% else -%}
| # | Severity | Title | File | Line |
|---|----------|-------|------|------|
{% for f in findings -%}
| {{ loop.index }} | {{ f.severity }} | {{ f.title }} | `{{ f.file | basename }}` | {{ f.line }} |
{% endfor %}
{%- endif %}

---

## Detailed Findings

{% if total_findings == 0 -%}
No findings to display.
{% else -%}
{% for f in findings %}
### {{ loop.index }}. [{{ f.severity }}] {{ f.title }}

| Field | Value |
|-------|-------|
| **Severity** | {{ f.severity }} |
| **File** | `{{ f.file }}:{{ f.line }}` |
| **Analyzer** | {{ f.analyzer }} |
| **Category** | {{ f.category }} |

**Description**

{{ f.description }}

**Recommendation**

{{ f.recommendation }}

{% if f.code_snippet -%}
**Code**

```solidity
{{ f.code_snippet }}
```
{% endif %}

---

{% endfor %}
{%- endif %}

## Disclaimer

This report was generated by an automated static analysis tool. While the
tool checks for common vulnerability patterns, it cannot guarantee the
absence of all security issues. Static analysis has inherent limitations:

- **False positives**: Some findings may not be actual vulnerabilities.
- **False negatives**: The tool may miss complex or novel attack vectors.
- **No formal verification**: Logic correctness is not verified.

A comprehensive security audit should include manual code review, formal
verification where applicable, and dynamic testing.

---

*Report generated by Smart Contract Security Scanner*
"""


def basename_filter(path: str) -> str:
    """Jinja2 filter to extract the filename from a path.

    Args:
        path: Full file path string.

    Returns:
        Just the filename portion.
    """
    return Path(path).name


def generate_report(
    input_data: dict,
    protocol_name: str = "Unknown Protocol",
) -> str:
    """Generate a Markdown audit report from scanner output.

    Args:
        input_data: Parsed JSON data from the scanner with 'stats' and 'findings' keys.
        protocol_name: Name of the protocol being audited.

    Returns:
        Rendered Markdown string.
    """
    stats = input_data.get("stats", {})
    findings = input_data.get("findings", [])

    severity_order = ["Critical", "High", "Medium", "Low", "Informational"]
    severity_counts: dict[str, int] = {sev: 0 for sev in severity_order}
    for sev, count in stats.get("by_severity", {}).items():
        if sev in severity_counts:
            severity_counts[sev] = count

    total_findings = len(findings)
    critical_count = severity_counts.get("Critical", 0)
    high_count = severity_counts.get("High", 0)
    analyzer_counts = stats.get("by_analyzer", {})

    # Set up Jinja2 environment
    env = Environment(loader=BaseLoader(), autoescape=False)
    env.filters["basename"] = basename_filter
    template = env.from_string(REPORT_TEMPLATE)

    rendered = template.render(
        protocol_name=protocol_name,
        timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        stats=stats,
        findings=findings,
        total_findings=total_findings,
        severity_order=severity_order,
        severity_counts=severity_counts,
        critical_count=critical_count,
        high_count=high_count,
        analyzer_counts=analyzer_counts,
        bar_char="#",
    )

    return rendered


def main() -> None:
    """CLI entry point for the report generator."""
    parser = argparse.ArgumentParser(
        description="Generate a formatted Markdown audit report from scanner JSON output.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            '  python report_generator.py --input findings.json --output report.md --protocol-name "Lido"\n'
            '  python report_generator.py --input findings.json --protocol-name "Aave V3"\n'
        ),
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Path to scanner JSON output file.",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Path to write the Markdown report (default: stdout).",
    )
    parser.add_argument(
        "--protocol-name",
        default="Unknown Protocol",
        help="Name of the protocol for the report header.",
    )

    args = parser.parse_args()

    # Read input JSON
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: Input file not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    try:
        input_data = json.loads(input_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in {args.input}: {e}", file=sys.stderr)
        sys.exit(1)

    # Generate report
    report = generate_report(input_data, protocol_name=args.protocol_name)

    # Output
    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(report, encoding="utf-8")
        print(f"Report written to: {args.output}")
    else:
        print(report)


if __name__ == "__main__":
    main()
